version: 2.1
jobs:
   build:
     docker:
       - image: aeristher/ansible-capstone-test
     steps:
        - checkout
        - run: |
            echo: ${CIRCLE_PULL_REQUEST}
            cp ./hosts /etc/ansible/hosts
            ansible-playbook ./playbooks/vim.yaml
