version: 2.1
jobs:
   build:
     docker:
       - image: aeristher/ansible-capstone-test
     steps:
        - checkout
        - run: |
            cp ./hosts.yaml /etc/ansible/hosts
            ansible-playbook ./vim.yaml
